### ISSUE TITLE
Error running

### ISSUE THREAD

**Issue by tinykidpro** [Warflop/FireShodanMap#3]
When I run, the following error occurs, help me fix it please, If possible, please take the video to me, Thank you very much:
#python fireshodan.py 
Traceback (most recent call last):
  File "fireshodan.py", line 56, in <module>
    firebase = pyrebase.initialize_app(config)
  File "/usr/local/lib/python2.7/dist-packages/pyrebase/pyrebase.py", line 28, in initialize_app
    return Firebase(config)
  File "/usr/local/lib/python2.7/dist-packages/pyrebase/pyrebase.py", line 48, in __init__
    self.credentials = ServiceAccountCredentials.from_json_keyfile_name(config["serviceAccount"], scopes)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/service_account.py", line 221, in from_json_keyfile_name
    client_credentials = json.load(file_obj)
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 2 column 9 - line 13 column 1 (char 9 - 2361)

**Comment by Warflop** [comment]
maybe it's a problem in your firebase access file, I'll try posting videos about the tools... :)
